---
title: "Untitled"
author: "Nina"
date: "2019年5月15日"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```
請將下面的TRUE換成FALSE, 並增加第5個元素其值為數字7
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]]<-"FALSE"
b[[5]]<-"7"
b
```
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
取出「期間」變數轉成date class
```{r}
library(lubridate)
exData3[[1]] <- ymd(exData3[[1]])
class(exData3[[1]])

```
增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）
```{r}
exData3$isAsiaCrisis <-ymd("1997-06-01") <= exData3$期間 &
  ymd("1998-12-01") >= exData3$期間
```
利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本
```{r}
exData3[exData3$isAsiaCrisis==T ,]
```
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
a<-transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[a,]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
class(utility_cobb_douglass)
utility_cobb_douglass(1,2,0.5,0.8)
```
```{r}
function1 <- function(x,.alpha){

value<-x+.alpha

return(value)
}
function1(1,2)
```
```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
subSample<-transcriptDataFinal[logiChosenStudent,]
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  sum(transcriptDataFinal$學期成績[logiChosenStudent]*
    transcriptDataFinal$學分數[logiChosenStudent])/
    sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
  return(GPA)
}
```
```{r}
gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```




































