---
title: '2019-04-17'
author: "Nina"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```
```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord

```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```
請取出前面成績單物件的個經元素
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
X<-成績單[["個經"]][[1]]
X
```
請取出姓名元素
```{r}
y<-studentRecord[["姓名"]]
y
```
請取出三年級學年平均成績
```{r}
z<-studentRecord[[4]][[3]]
z
```
同時取出greenBox及redBox兩個元素
```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```
取出“paper”
```{r}
extract1 <- plasticContainer[c("greenBox")][[1]][[1]]
extract1
extract2 <- plasticContainer[[c("greenBox")]][[1]]
extract2
```
```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
成績單
成績單[c(FALSE,TRUE,TRUE)]
```
$.跟[[]]相同
```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```
```{r}
your_github_username <- "Nina2089"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```
birthday只能有8位元，str_length()可計算每個元素的位元長度。請產生一個logical vector稱為logiCorrect，TRUE表示剛好8位元
```{r}
str_length(birthday)
logiCorrect<-str_length(birthday)==8
logiCorrect
```
只留下birthday輸入正確的人，請統計各別片名支持人數
```{r}
validFavoriteTwo<-favoriteTwo[logiCorrect]
validFavoriteTwo
```









































