---
title: '2019-03-20'
author: ""
date: "3/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
b<-"你好"
```
```{r}
bVector<-c("你好","How are you?")
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```
以上對白請把它改成:
小明說：'明天不用上課。'
小花說：'真的嗎？'
```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```
# 加總向量內的所有元素值
```{r}
sum(aLogical)
```

```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```
```{r}
typeof(studentMajors)
```
```{r}
levels(studentMajors)
```
```{r}
birthplace <- factor(c("台北市","新北市","桃園市","台北市","桃園市"))
class(birthplace)
levels(birthplace)
as.integer(birthplace)
```
levels顯示的類別名稱（categorical values）順序整數值即R真正儲存的內容
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) 
```
# 無法進行數值運算
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger)
```
# 可以進行數值運算
```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms(
  c("1970-01-01 00:02:53")
)
class(dtObject)
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```
```{r}
typeof(dtObject)
as.double(dtObject)
```

```{r}
Sys.timezone()
```


