---
title: "Untitled"
author: "Nina"
date: "2019年5月29日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(lubridate)
now2<- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
now2()
```
```{r}
browseURL("https://www.ntpu.edu.tw")
```
請寫一個textbookURL函數，執行textbookURL()會自動開啟課程網頁。
```{r}
textbookURL <- function(){
  browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#defaults")
}

textbookURL()
```
想要輸出GPA及該名學生成績單子樣本subSample
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent

gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
gpa_fun2("92aS67fee") -> outputValue
outputValue$平均成績
outputValue$成績單
```
創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量
```{r}
demand_supply_fun <- function(P,a,b,c,d){
  QS <- a + b*P
  QD <- c - d*P
  return(
    list(
      供給量 = QS,
      需求量 = QD,
      超額供給量 = QS - QD
    )
  )
}
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
a<-0
b<-1
supply_fun <- function(P,a,b){
  Qs <- a+b*P
  return(Qs)
}
supply_fun(P=-1,0,1)
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```
修改範例2的gpa_fun, 若輸入學號不存在則在螢幕顯示“查無此學號”
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID!="92aS67fee"){
    message("查無此學號")
  } else {
  return(GPA)}
}

gpa_fun("92aS67fee") 
gpa_fun("aa829838s")
```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P必需大於等於",-a/b,"(即-a/b值)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```

```{r}
5 %% 3
```


```{r}
fizzbuzz <- function(input){
  zeroRemBy3 <- input %% 3 == 0
  zeroRemBy5 <- input %% 5 == 0
  if(zeroRemBy3 & !zeroRemBy5){
    return("fizz")
  } else if(zeroRemBy5 & !zeroRemBy3){
    return("buzz")
  } else if(zeroRemBy5 & zeroRemBy3){
    return("fuzzbuzz")
  } else {
    message("other situation")
  }
}
```

```{r}
fizzbuzz(7)
fizzbuzz(6) 
fizzbuzz(5) 
fizzbuzz(15)
```

```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}
```


## any all

```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
```

```{r}
if(a>2) {
  print("a大於2")
}
```


要每個a元素都> 2, 使用all()
```{r}
a
a>2
all(a>2)
any(a>2)
```


```{r}
if(all(a>2)){
  print("a大於2")
}
```


```
if(studentID %in% transcriptDataFinal$學號)
```
可以用
```
if(any(studentID==transcriptDataFinal$學號))
```

## Environment

```{r}
a <- 3
testfun <- function(x){
  y <- a/4
  output <- x*y
  return(output)
}
testfun(2)
a <- 4
testfun(2)
```




```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent
    subSample <- transcriptDataFinal[logiChosenStudent,]
    sum(subSample$學期成績*subSample$學分數)/
      sum(subSample$學分數) -> GPA
    return(GPA)
  } else {
    message("查無此學號")
  }
}
gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```


```{r}
transcriptDataFinal[transcriptDataFinal$學號 != "92aS67fee",] ->
  transcriptDataFinal
```

```{r}
gpa_fun("92aS67fee") # 顯示82.85276
```

```{r}
gpa_fun4 <- function(studentID,transcriptDataFinal){
  if(studentID %in% transcriptDataFinal$學號){
    transcriptDataFinal$學號==studentID -> logiChosenStudent
    subSample <- transcriptDataFinal[logiChosenStudent,]
    sum(subSample$學期成績*subSample$學分數)/
      sum(subSample$學分數) -> GPA
    return(GPA)
  } else {
    message("查無此學號")
  }
}
```

```{r}
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
gpa_fun4("92aS67fee",transcriptDataFinal)
```




























