---
title: '2019-03-27'
author: ""
date: "3/27/2019"
output: html_document
---
```{r}
library(lubridate)
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
class(dtObject)
```
```{r}
Sys.timezone()
```
顯示時區
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
```
```{r}
typeof(twDateTime)
as.integer(twDateTime)
as.integer(LisbonDateTime)
```
as.interger可以算差多少時間
```{r}
googletime<- mdy_hms ("03-27-2019 15:53:00",tz="Asia/Taipei")
```
```{r}
dtobject2<-ymd("2018-09-11")
dtobject3<-mdy("March 3, 2019")
```
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```
```{r}
class(a+bL)
class(aL+bL)
class(a-bL)
class(a*bL)
```
```{r}
c <- 4

c+a
```
```{r}
a^b
a %% b
```
餘數：%%
次方：^ 或 **
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime+1
```
```{r}
dtobject4<-ymd("2019-08-11")
dtobject5<-ymd("2000-02-01")
dtobject4-dtobject5
```
```{r}
class(dtobject4-dtobject5)
as.numeric(dtobject4-dtobject5)
```
```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
```
明年此時+years()
```{r}
startingDate + dyears(1)
```
經過一年(365天)+dyears()
```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```
```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x>=y
x<=y
x==y
```
x=y與x<-y相同
```{r}
x2>4
```
```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
x3>y3
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```
%in%: 屬於
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)
x2==y2
```
```{r}
is.na(x2)
```
```{r}
sum(x2)
sum(x2,na.rm=F)
sum(x2,na.rm =T)
```
na.rm 
